name: libession-util-nodejs build test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-13, ubuntu-22.04]
    env:
      SIGNAL_ENV: production
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global core.autocrlf false

      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        if: runner.os == 'Windows'

        # Note: we will be able to get rid of this once the whole tree of submodules has the latest version of oxen-logging
        # We'd need oxen-libquic to be updated to have the commit `bc7167f90e71643b43c2ea9cf7d1fefa5045f8d4`, but we don't want to
        # update libquic that late.
        # We will soon, though :tm:
      - name: Apply patches
        if: runner.os == 'Windows'
        shell: bash
        run: |
          yarn naughty-patch

      - name: generate fake src/version.h so we can try to build
        shell: bash
        run: yarn update_version


      - name: build libsession-util-nodejs
        shell: bash
        run: yarn install --frozen-lockfile
